/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#adc6ff",
        "primary": "#dbfcff",
        "surface-dim": "#0b1326",
        "surface-container-lowest": "#060e20",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-surface": "#dae2fd",
        "background": "#0b1326",
        "on-secondary-fixed": "#001a42",
        "on-primary-container": "#006970",
        "inverse-on-surface": "#283044",
        "surface-container-high": "#222a3d",
        "on-secondary-fixed-variant": "#004395",
        "on-primary-fixed-variant": "#004f54",
        "surface-variant": "#2d3449",
        "tertiary-fixed-dim": "#4edea3",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#00dbe9",
        "on-primary": "#00363a",
        "on-tertiary-fixed": "#002113",
        "inverse-primary": "#006970",
        "primary-fixed": "#7df4ff",
        "surface-container": "#171f33",
        "on-primary-fixed": "#002022",
        "on-error-container": "#ffdad6",
        "on-secondary": "#002e6a",
        "error-container": "#93000a",
        "secondary-fixed": "#d8e2ff",
        "surface": "#0b1326",
        "secondary": "#adc6ff",
        "outline": "#849495",
        "surface-container-low": "#131b2e",
        "outline-variant": "#3b494b",
        "on-surface-variant": "#b9cacb",
        "on-background": "#dae2fd",
        "secondary-container": "#0566d9",
        "tertiary": "#d8ffe7",
        "on-surface": "#dae2fd",
        "on-tertiary-container": "#006d4a",
        "surface-tint": "#00dbe9",
        "surface-bright": "#31394d",
        "on-secondary-container": "#e6ecff",
        "primary-container": "#00f0ff",
        "surface-container-highest": "#2d3449",
        "tertiary-container": "#65f2b5",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary": "#003824"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "container-max": "1200px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["1.75rem", { lineHeight: "1.2", fontWeight: "700" }],
        "code-sm": ["0.875rem", { lineHeight: "1.5", fontWeight: "500" }],
        "headline-lg": ["2.25rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display": ["4rem", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["1.125rem", { lineHeight: "1.7", fontWeight: "400" }],
        "headline-md": ["1.5rem", { lineHeight: "1.4", fontWeight: "600" }],
        "label-caps": ["0.75rem", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-md": ["1rem", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
